config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'sesiones/new'

  get 'usuarios/new'

  # root to: "movimientos#index"

  get '/informes/cuentas/saldos', controller: :cuentas, action: :saldos
  resources :cuentas

  get '/movimientos/carga_masiva', controller: :movimientos, action: :carga_masiva
  post '/movimientos/carga_masiva', controller: :movimientos, action: :grabar_carga_masiva
  get '/movimientos/carga_masiva/nuevo_movimiento', controller: :movimientos, action: :nuevo_movimiento_masivo
  get '/movimientos/carga_masiva/sumar', controller: :movimientos, action: :sumar
  get '/movimientos/consultas/entre-fechas', controller: :movimientos, action: :entre_fechas
  post '/movimientos/consultas/entre-fechas', controller: :movimientos, action: :cons_entre_fechas
  # get '/movimientos/cuenta', action: :list, on: :collection, as: :cons_por_cta
  resources :movimientos do
    # get 'cuenta/:id(/pag/:page)', action: :list, on: :collection
    get 'cuenta', action: :list, on: :collection, as: :cons_por_cta
  end

  resources :transacciones do
    member do
      get 'select_by_tipoid'
    end
    get 'tipo/:id(/pag/:page)', action: :list, on: :collection
  end
  resources :tipos_transacciones do
    get 'pag/:page', action: :index, on: :collection
  end

  delete "logout" => "sesiones#destroy", :as => "logout"
  get "login" => "sesiones#new", :as => "login"
  # get "signup" => "usuarios#new", :as => "signup"
  root :to => "sesiones#new"
  resources :usuarios, except: [:show, :destroy] do
    member do
      get 'change_pwd'
      patch 'update_pwd'
      patch 'reset_pwd'
    end
  end
  resources :sesiones, only: [:create, :new, :destroy]
end

app/views/controls/_checkbox.html.erb
<% if checkbox %>
  <span class="glyphicon glyphicon-check"></span>          
<% else %>
  <span class="glyphicon glyphicon-unchecked"></span>
<% end %>

app/views/controls/_form_actions.html.erb
<div class="actions">
  <%= form.submit class: 'btn btn-default', role: 'button'%>
  <%= link_to 'Cancelar', cancelar_path, class: 'btn btn-default', role: 'button' %>    
</div>  

app/views/controls/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" rel="home" href="#" title="Gastos">
          <%= image_tag "new-logo.png", size: "32x32", style: "margin-top: -7px; margin-right: -10px;" %>
      </a>
      <span style="color: #fff; font-weight: bold; font-size: 1.75em;" class="navbar-brand">
        Gastos
      </span>
    </div>


    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <%= link_to movimientos_path, class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
            Movimientos <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'Listado general', movimientos_path %></li>
            <li><%= link_to 'Entre fechas', movimientos_consultas_entre_fechas_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <%= link_to cuentas_path, class: "dropdown-toggle", data: {toggle: "dropdown"} do %>
            Cuentas <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to 'Listado general', cuentas_path %></li>
            <li><%= link_to 'Saldos de cuentas', informes_cuentas_saldos_path %></li>
          </ul>
        </li>
        <li><%= link_to 'Tipos de transacciones', tipos_transacciones_path%></li>
        <li><%= link_to 'Transacciones', transacciones_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-user"></span>
          <%= current_user.nombre %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "Cambiar contraseña", change_pwd_usuario_path(current_user) %>
            </li>
            <% if current_user.es_admin %>
            <li>
              <%= link_to "Editar usuarios", usuarios_path %>
            </li>
            <% end %>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <span class="glyphicon glyphicon-log-out"></span> Cerrar sesión
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>