config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'sesiones/new'

  get 'usuarios/new'

  # root to: "movimientos#index"

  get '/informes/cuentas/saldos', controller: :cuentas, action: :saldos
  resources :cuentas

  get '/movimientos/carga_masiva', controller: :movimientos, action: :carga_masiva
  post '/movimientos/carga_masiva', controller: :movimientos, action: :grabar_carga_masiva
  get '/movimientos/carga_masiva/nuevo_movimiento', controller: :movimientos, action: :nuevo_movimiento_masivo
  get '/movimientos/carga_masiva/sumar', controller: :movimientos, action: :sumar
  get '/movimientos/consultas/entre-fechas', controller: :movimientos, action: :entre_fechas
  post '/movimientos/consultas/entre-fechas', controller: :movimientos, action: :cons_entre_fechas
  # get '/movimientos/cuenta', action: :list, on: :collection, as: :cons_por_cta
  resources :movimientos do
    # get 'cuenta/:id(/pag/:page)', action: :list, on: :collection
    get 'cuenta', action: :list, on: :collection, as: :cons_por_cta
  end

  resources :transacciones do
    member do
      get 'select_by_tipoid'
    end
    get 'tipo/:id(/pag/:page)', action: :list, on: :collection
  end
  resources :tipos_transacciones do
    get 'pag/:page', action: :index, on: :collection
  end

  delete "logout" => "sesiones#destroy", :as => "logout"
  get "login" => "sesiones#new", :as => "login"
  # get "signup" => "usuarios#new", :as => "signup"
  root :to => "sesiones#new"
  resources :usuarios, except: [:show, :destroy] do
    member do
      get 'change_pwd'
      patch 'update_pwd'
      patch 'reset_pwd'
    end
  end
  resources :sesiones, only: [:create, :new, :destroy]
end

app/controllers/sesiones_controller.rb
class SesionesController < ApplicationController
	skip_before_action :authorize, only: [:new, :create]
	layout false

  def new
  	if current_user
  		redirect_to action: :index, controller: :movimientos
  	end
  end

  def create
		user = Usuario.authenticate(params[:email], params[:password])
	  if user
	    session[:usuario_id] = user.id
	    if session[:intented_params]
		    redirect_to action: session[:intended_action],
										controller: session[:intended_controller],
										params: (session[:intented_params]||{})
	   	elsif session[:intended_action]
		    redirect_to action: session[:intended_action],
										controller: session[:intended_controller]
			else
				redirect_to root_url
	    end
	  else
	    flash[:error] = "El usuario o la contraseña son incorrectos"
	    redirect_to root_url
	  end
  end

  def destroy
  	session[:usuario_id] = nil
  	session[:intended_action] = nil
  	session[:intended_controller] = nil
  	session[:intented_params] = nil
  	redirect_to root_url #, :notice => "Logged out!"
  end
end

app/helpers/sesiones_helper.rb
module SesionesHelper
end

app/views/sesiones/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= "Gastos - Iniciar sesión" %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<style type="text/css">
			body {
				background-color: #eee;
			}

			h2 {
				font-weight: bold;
				text-align: center;
			}

			h2, .checkbox {
				margin-bottom: 30px;
			}

			.panel {
		    position: absolute;
		    top: 40%;
		    left: 50%;
		    transform: translateX(-50%) translateY(-50%);
		    width: 400px;
			}
		</style>
  </head>
  <body>
    <div class="container-fluid">
			<div class="container body-content">
				<div class="panel panel-primary">
					<div class="panel-body">
						<%= form_tag sesiones_path do %>
							<h2 class="text-primary">Gastos</h2>
						  <div><%= render 'notice' %></div>
							<div class="form-group">
							  <p>
							    <%= label_tag :email, "Usuario o EMail:", class: "sr-only" %>
							    <%= text_field_tag :email, params[:email], class: "form-control", placeholder: "Usuario o Email", required: true, autofocus: true, type: "email" %>
							  </p>
							  <p>
							    <%= label_tag :password, "Contraseña:", class: "sr-only" %>
							    <%= password_field_tag :password, nil, class: "form-control", placeholder: "Contraseña" %>
							  </p>
							  <div class="checkbox">
				          <label><input type="checkbox" value="remember-me" style="margin-top: 0;"> Recuérdame</label>
							  </div>
							  <p>
							  	<%= submit_tag "Iniciar sesión", class: "btn btn-lg btn-primary btn-block", role: "button" %>
						  	</p>
						  </div>
						<% end %>
					</div>
				</div>
			</div>
    </div>
  </body>
</html>