config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'sesiones/new'

  get 'usuarios/new'

  # root to: "movimientos#index"

  get '/informes/cuentas/saldos', controller: :cuentas, action: :saldos
  resources :cuentas

  get '/movimientos/carga_masiva', controller: :movimientos, action: :carga_masiva
  post '/movimientos/carga_masiva', controller: :movimientos, action: :grabar_carga_masiva
  get '/movimientos/carga_masiva/nuevo_movimiento', controller: :movimientos, action: :nuevo_movimiento_masivo
  get '/movimientos/carga_masiva/sumar', controller: :movimientos, action: :sumar
  get '/movimientos/consultas/entre-fechas', controller: :movimientos, action: :entre_fechas
  post '/movimientos/consultas/entre-fechas', controller: :movimientos, action: :cons_entre_fechas
  # get '/movimientos/cuenta', action: :list, on: :collection, as: :cons_por_cta
  resources :movimientos do
    # get 'cuenta/:id(/pag/:page)', action: :list, on: :collection
    get 'cuenta', action: :list, on: :collection, as: :cons_por_cta
  end

  resources :transacciones do
    member do
      get 'select_by_tipoid'
    end
    get 'tipo/:id(/pag/:page)', action: :list, on: :collection
  end
  resources :tipos_transacciones do
    get 'pag/:page', action: :index, on: :collection
  end

  delete "logout" => "sesiones#destroy", :as => "logout"
  get "login" => "sesiones#new", :as => "login"
  # get "signup" => "usuarios#new", :as => "signup"
  root :to => "sesiones#new"
  resources :usuarios, except: [:show, :destroy] do
    member do
      get 'change_pwd'
      patch 'update_pwd'
      patch 'reset_pwd'
    end
  end
  resources :sesiones, only: [:create, :new, :destroy]
end

app/models/movimiento.rb
class Movimiento < ApplicationRecord
  paginates_per 50

  belongs_to :transaccion
  belongs_to :cuenta
  belongs_to :empresa
  belongs_to :usuario

  # attr_accessor :usuario

  validates_presence_of :cuenta_id, :fecha_mov, :transaccion_id, :importe
  validates_numericality_of :importe, greater_than: 0
  validates_inclusion_of :transaccion_id, in: :transacciones

  #has_many :item_movimiento
  #attr_accesor :item_movimiento_id

  attr_writer :saldo
  attr_accessor :agrupar

  def saldo
  	@saldo || 0
  end

  def es_debito
  	transaccion.es_debito
  end

  def importe_real
  	(es_debito)? -importe : importe
  end

  def tipo_transaccion_id
  	(transaccion.nil?)? 0 : transaccion.tipo_transaccion_id
  end

  def items
    logger.debug "@items = #{@items}"
    @items || [Movimiento.new]
  end

  def items=(values)
    logger.debug '- items=(values) -'
    @items, @errores = [], []
    values.each do |i|
      logger.debug i.to_yaml
      m = Movimiento.new(cuenta_id: cuenta_id, fecha_mov: fecha_mov,
            transaccion: Transaccion.find_by_id(i[:transaccion_id]),
            importe: i[:importe])
      @items << m
    end
  end

  def save_items(empresa_id)
    logger.debug "- save_items -"
    @items.each do |m|
      m.usuario = usuario
      m.empresa_id = empresa_id
      if not m.valid?
        @errores = (@errores + m.errors.full_messages).uniq
        logger.debug "errores = #{m.errors.to_hash(true)}"
        logger.debug "@errores = #{@errores}"
      end
    end
    if @errores.blank?
      if agrupar
        logger.debug 'graba agrupando'
        items_agrup = @items.group_by { |m| m.transaccion_id }
        items_agrup.map do |k,v|
          total = items_agrup[k].sum { |m1| m1.importe }
          m = @items.find{|m1| m1.transaccion_id == k }
          m2 = Movimiento.new(m.attributes)
          m2.importe = total
          m2.empresa_id = empresa_id
          m2.save
        end
      else
        logger.debug 'grabando sin agrupar'
        @items.each do |i|
          i.empresa_id = empresa_id
          i.save
        end
      end
    else
      logger.debug "cargando errores - errors = #{errors}"
      errors.clear
      @errores.each{|e| errors.add(:base, e)}
    end
    logger.debug "@errores.blank? = #{@errores.blank?} | @errores = #{@errores} | errors = #{errors}"
    return @errores.blank?
  end

  def transacciones
    usuario.transacciones.all_for_select.map { |t| t[1] }
  end

  def self.movimientos_entre_fechas(fecha_desde, fecha_hasta, cuenta_id)
    movs = self
            .joins(:empresa)
            .joins(transaccion: :tipo_transaccion)
            .joins(:cuenta)
            .select("movimientos.*, transacciones.descripcion AS trx_desc, transacciones.es_debito, 
              tipos_transacciones.descripcion AS ttrx_desc, cuentas.saldo_inicial")
            .where("empresas.id = ? and movimientos.cuenta_id = ? and movimientos.fecha_mov >= ? and movimientos.fecha_mov <= ?",
              Usuario.current_user.empresa_id, cuenta_id, fecha_desde, fecha_hasta)
    return movs
  end

  def self.movimientos_con_saldo(fecha_desde, fecha_hasta, cuenta_id)
    movs = movimientos_entre_fechas(fecha_desde, fecha_hasta, cuenta_id)
            .order(fecha_mov: :asc, created_at: :asc)
    result = []
    if movs.any?
      anteriores = Usuario.current_user.movimientos.joins(:transaccion)
                    .where("movimientos.cuenta_id = ? and movimientos.created_at < ?", cuenta_id, movs.first.created_at)
      debitos = anteriores.where("transacciones.es_debito = ?", true).sum(:importe)
      creditos = anteriores.where("transacciones.es_debito = ?", false).sum(:importe)
      saldo_anterior = movs.first.saldo_inicial + creditos - debitos
      mov_sdoant = movs.first.dup
      mov_sdoant.saldo = saldo_anterior
      movs.each do |m|
        if m.es_contrasiento
          m.saldo = saldo_anterior
        else
          if m.es_debito
            m.saldo = saldo_anterior - m.importe
          else
            m.saldo = saldo_anterior + m.importe
          end
        end
        saldo_anterior = m.saldo
      end
      mov_sdoant.class_eval { attr_accessor :trx_desc }
      mov_sdoant.trx_desc = " - Saldo anterior -"
      mov_sdoant.importe = nil
      mov_sdoant.transaccion_id = nil
      mov_sdoant.fecha_mov = nil
      result = movs.to_a
      result.unshift(mov_sdoant)
    end
    return result
  end

  def self.movimientos_con_saldo_por_usuario(fecha_desde, fecha_hasta, cuenta_id)
    movs = movimientos_entre_fechas(fecha_desde, fecha_hasta, cuenta_id)
            .joins(:usuario)
            .select("usuarios.nombre AS nombre_usuario")
            .order("nombre_usuario ASC", fecha_mov: :asc, created_at: :asc)
    return movs
  end
end

app/controllers/movimientos_controller.rb
class MovimientosController < ApplicationController
  before_action :set_movimiento, only: [:show, :edit, :update, :destroy]
  before_action :set_tipos_transacciones, only: [:new, :create, :edit, :update]

  # GET /movimientos
  # GET /movimientos.json
  def index
    @fecha_hasta = Date.today
    @fecha_desde = @fecha_hasta - 30
  end

  def list
    cuenta_id = params[:id].to_i
    fecha_desde = helpers.str_to_date(params[:fecha_desde])
    fecha_hasta = helpers.str_to_date(params[:fecha_hasta])
    @movimientos = Movimiento
                     .movimientos_entre_fechas(fecha_desde, fecha_hasta, cuenta_id)
                     .order(fecha_mov: :desc, created_at: :desc, cuenta_id: :asc)
                     .page(params[:page])
  end

  # GET /movimientos/1
  # GET /movimientos/1.json
  def show
  end

  # GET /movimientos/new
  def new
    @movimiento = Movimiento.new(fecha_mov: Date.today)
    @transacciones = []
  end

  # GET /movimientos/1/edit
  def edit
    if @movimiento.tipo_transaccion_id > 0
      @transacciones = current_user.transacciones
                          .where(tipo_transaccion_id: @movimiento.tipo_transaccion_id)
                          .order(:descripcion)
                          .map { |t| [t.descripcion, t.id] }
    else
      @transacciones = []
    end
  end

  # POST /movimientos
  # POST /movimientos.json
  def create
    @movimiento = Movimiento.new(movimiento_params)
    @movimiento.empresa_id = current_user.empresa_id
    @movimiento.usuario = current_user
    flash[:cuenta_id] = @movimiento.cuenta_id

    respond_to do |format|
      if @movimiento.save
        format.html { redirect_to movimientos_url, notice: 'El movimiento se creó correctamente.' }
        format.json { render :show, status: :created, location: @movimiento }
      else
        @transacciones = current_user.transacciones.all_for_select(@movimiento.tipo_transaccion_id)
        format.html { render :new }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movimientos/1
  # PATCH/PUT /movimientos/1.json
  def update
    respond_to do |format|
      if @movimiento.update(movimiento_params)
        flash[:cuenta_id] = @movimiento.cuenta_id
        format.html { redirect_to movimientos_url, notice: 'El movimiento se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @movimiento }
      else
        @transacciones = current_user.transacciones.all_for_select(@movimiento.tipo_transaccion_id)
        format.html { render :edit }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movimientos/1
  # DELETE /movimientos/1.json
  def destroy
    respond_to do |format|
      if @movimiento.update(es_contrasiento: true, usuario: current_user)
        format.html { redirect_to movimientos_url, notice: 'El movimiento se contrasentó correctamente.' }
        format.json { head :no_content }
      else
        format.html { redirect_to movimientos_path, error: @movimiento.errors.full_messages.join(" ") }
        format.json { render json: @movimiento.errors, status: :unprocessable_entity }
      end
    end
  end

  def carga_masiva
    @movimiento = Movimiento.new(fecha_mov: Date.today)
    render 'movimientos/carga_masiva/new'
  end

  def grabar_carga_masiva
    @movimiento = Movimiento.new(movimiento_masivo_params)
    logger.debug "current_user.empresa_id = #{current_user.empresa_id}"
    @movimiento.empresa_id = current_user.empresa_id
    @movimiento.usuario = current_user
    flash[:cuenta_id] = @movimiento.cuenta_id
    logger.debug "agrupar = #{@movimiento.agrupar.to_s}"
    respond_to do |format|
      if @movimiento.save_items(current_user.empresa_id)
        format.html { redirect_to movimientos_url, notice: 'Los movimientos se crearon correctamente.' }
      else
        @transacciones = current_user.transacciones.all_for_select(@movimiento.tipo_transaccion_id)
        format.html { render 'movimientos/carga_masiva/new' }
      end
    end
  end

  def nuevo_movimiento_masivo
    @movimiento = Movimiento.new(fecha_mov: Date.today)
  end

  def sumar
    p = params.permit({items: [:trx, :importe]})
    tmp = []
    p['items'].each { |k,v| tmp << v }
    @cantidad = p['items'].to_h.count
    @total = tmp.inject(0){|sum,x| sum + x["importe"].to_f }
  end

  # GET '/movimientos/consultas/entre-fechas'
  def entre_fechas
    @movimiento = MovEntreFechasSearch.new
    render 'movimientos/reportes/cons_entre_fechas/index'
  end

  # POST '/movimientos/consultas/entre_fechas'
  def cons_entre_fechas
    p = params.require(:mov_entre_fechas_search).permit(:fecha_desde, :fecha_hasta, :cuenta_id, :tipo_informe)
    m = MovEntreFechasSearch.new(p)
    if m.valid?
      pdf = MovEntreFechasPdf.new(m, view_context)
      if not pdf.nil?
        send_data pdf.render, filename: pdf.file_name,
                              type: "application/pdf",
                              disposition: "inline"
      end
    else
      render action: 'entre_fechas'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movimiento
      @movimiento = Movimiento.find(params[:id])
      @movimiento.usuario = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movimiento_params
      params.require(:movimiento).permit(:fecha_mov, :transaccion_id, :importe, :cuenta_id)
    end

    def set_tipos_transacciones
      @tipos_transacciones = current_user.tipos_transacciones.where(habilitado: true).map { |t| [t.descripcion, t.id] }
    end

    def movimiento_masivo_params
      params.require(:movimiento).permit(:fecha_mov, :cuenta_id, :agrupar, {items: [:transaccion_id, :importe]})
    end
end

app/helpers/movimientos_helper.rb
module MovimientosHelper
end

app/views/movimientos/_form.html.erb
<%= form_for(@movimiento) do |f| %>
  <%= render 'errores', partial: true, model: movimiento, model_name: 'El movimiento' %>

  <div class="form-group">
    <%= f.label :cuenta_id %>
    <%= f.select :cuenta_id, options_for_select(current_user.cuentas.all_for_select, @movimiento.cuenta_id),
          {prompt: t('helpers.select.prompt')}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :fecha_mov %><br/>
    <%#= f.date_select :fecha_mov %>
    <%= f.text_field :fecha_mov, value: format_date(@movimiento.fecha_mov), class: "date-picker" %>
    <!--input type="text" name="form-control" class="date-picker"-->
  </div>

  <div class="form-group tipo-transaccion">
    <%= label_tag "tipo_transaccion_id", 'Tipo de transacción' %>
    <%= select_tag "tipo_transaccion_id", options_for_select(TipoTransaccion.all_for_select(current_user),
          @movimiento.tipo_transaccion_id), {prompt: t('helpers.select.prompt'), class: "form-control"} %>
  </div>

  <div id="transacciones" class="form-group transaccion">
    <%= f.label :transaccion_id %>
    <%= image_tag "ajax-loader.gif", { alt: "Cargando...", size: "25", id: "loader", class: 'hide-on-load'} %>
    <%= f.select :transaccion_id, options_for_select(@transacciones, @movimiento.transaccion_id),
          {prompt: t('helpers.select.prompt')}, {class: 'form-control'} %>
  </div>

  <div class="form-group">
    <%= f.label :importe %>
    <%= f.text_field :importe, value: currency_for_edition(@movimiento.importe), class: 'form-control text-right number' %>
  </div>

  <%= render partial: "controls/form_actions", locals: { form: f, cancelar_path: movimientos_path} %>
<% end %>

app/views/movimientos/_list.html.erb
<% if @movimientos.any? %>
  <table class="table table-striped table-responsive table-bordered">
    <thead>
      <tr>
        <th class="text-center">Fecha</th>
        <th class="text-center">Rubro</th>
        <th class="text-center">Transacción</th>
        <th class="text-center">Contr.</th>
        <th class="text-center">Importe</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @movimientos.each do |movimiento| %>
        <tr>
          <td class="col-sm-2"><%= I18n.localize movimiento.fecha_mov, format: :fecmov %></td>
          <td><%= movimiento.transaccion.tipo_transaccion.descripcion %></td>
          <td><%= movimiento.transaccion.descripcion %></td>
          <td class="text-center"><%= render partial: "controls/checkbox", object: movimiento.es_contrasiento %></td>
          <td class="text-right"><%= number_to_currency movimiento.importe %></td>
          <td class="text-center">
            <% if not movimiento.es_contrasiento %>
              <%= link_to edit_movimiento_path(movimiento) do %>
                <span class="glyphicon glyphicon-edit"></span>
              <% end %>
              <%= link_to movimiento, method: :delete, data: { confirm: '¿Está seguro que desea contrasentar el movimiento?' } do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            <% end -%>
          </td>          
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @movimientos, remote: true, window: 20 %>
<% else %>
  <div id="notas-empty" class="row">
    <div class="alert alert-success text-center col-sm-4 col-sm-offset-4">
      Todavía no hay movimientos cargados.
    </div>
  </div>
<% end %>

app/views/movimientos/carga_masiva.html.erb
<% content_for :title, "Carga masiva de movimientos" %>

<h1>Carga masiva de movimientos</h1>

<%= render 'form', movimiento: @movimiento %>

app/views/movimientos/edit.html.erb
<h1>Movimiento</h1>

<%= render 'form', movimiento: @movimiento %>

app/views/movimientos/index.html.erb
<% content_for :title, "Movimientos" %>

<div id="index_movimientos">

  <div class="row">
    <h1 class="col-sm-3">Movimientos</h1>
    <div class="col-sm-6"><%= render 'notice' %></div>
    <div id="menu-abm" class="col-sm-3 text-right">
      <%= link_to 'Nuevo movimiento', new_movimiento_path, class: 'btn btn-default', role: 'button' %>
      <%= link_to "Carga masiva", movimientos_carga_masiva_path, class: 'btn btn-default', role: 'button' %>
    </div>
  </div>

  <div class="row movidxcta">
    <%= form_tag cons_por_cta_movimientos_path, remote: true, method: :get, class: "form-inline" do  %>

      <div class="col-sm-12 form-group">
        <%= label_tag :cuenta_id, "Cuenta:" %>
        <%= select_tag "id", options_for_select(current_user.cuentas.all_for_select, flash[:cuenta_id]),
              {class: "form-control", style: "display: inline; max-width: 40%; margin-rigth: 10px;"} %>
        <span style="width: 10px; display: inline-block;"></span>

        <%= label_tag "Período: " %>
        <%= text_field_tag "fecha_desde", format_date(@fecha_desde), class: "form-control date-picker" %>
         al 
        <%= text_field_tag "fecha_hasta", format_date(@fecha_hasta), class: "form-control date-picker" %>
        <span style="width: 10px; display: inline-block;"></span>

        <%= submit_tag "Consultar", class: 'btn btn-default', role: 'button'%>
        <%= image_tag "ajax-loader.gif", { alt: "Cargando...", size: "30", id: "loader", class: "hide-on-load" } %>
      </div>

    <% end %>    
  </div>

  <br/>

  <div id="list"></div>
</div>

app/views/movimientos/list.js.erb
$("#index_movimientos #list").html('<%= escape_javascript render "list" %>');
$('#index_movimientos #loader').hide();
$('.pagination a').click(function () {
	$('.movidxcta #loader').show();
});

app/views/movimientos/new.html.erb
<% content_for :title, "Nuevo Movimiento" %>

<h1>Nuevo Movimiento</h1>

<%= render 'form', movimiento: @movimiento %>

app/views/movimientos/nuevo_movimiento_masivo.js.erb
function getRow(argument) {
	var h = $('<%= escape_javascript render "movimientos/carga_masiva/movimiento", movimiento: @movimiento %>');
	h.find('#loader').hide();
	return h;
}

//$("form #movimientos").append(getRow());
$("form #movimientos .row").last().before(getRow());
$('#nuevo-mov .loader').hide();

app/views/movimientos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha mov:</strong>
  <%= @movimiento.fecha_mov %>
</p>

<p>
  <strong>Transaccion:</strong>
  <%= @movimiento.transaccion %>
</p>

<p>
  <strong>Importe:</strong>
  <%= @movimiento.importe %>
</p>

<%= link_to 'Edit', edit_movimiento_path(@movimiento) %> |
<%= link_to 'Back', movimientos_path %>

app/views/movimientos/sumar.js.erb
$('.total h4 > span').html('<%= "#{pluralize(@cantidad, "movimiento", "movimientos")} por #{number_to_currency(@total)} "%>');