config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  get 'sesiones/new'

  get 'usuarios/new'

  # root to: "movimientos#index"

  get '/informes/cuentas/saldos', controller: :cuentas, action: :saldos
  resources :cuentas

  get '/movimientos/carga_masiva', controller: :movimientos, action: :carga_masiva
  post '/movimientos/carga_masiva', controller: :movimientos, action: :grabar_carga_masiva
  get '/movimientos/carga_masiva/nuevo_movimiento', controller: :movimientos, action: :nuevo_movimiento_masivo
  get '/movimientos/carga_masiva/sumar', controller: :movimientos, action: :sumar
  get '/movimientos/consultas/entre-fechas', controller: :movimientos, action: :entre_fechas
  post '/movimientos/consultas/entre-fechas', controller: :movimientos, action: :cons_entre_fechas
  # get '/movimientos/cuenta', action: :list, on: :collection, as: :cons_por_cta
  resources :movimientos do
    # get 'cuenta/:id(/pag/:page)', action: :list, on: :collection
    get 'cuenta', action: :list, on: :collection, as: :cons_por_cta
  end

  resources :transacciones do
    member do
      get 'select_by_tipoid'
    end
    get 'tipo/:id(/pag/:page)', action: :list, on: :collection
  end
  resources :tipos_transacciones do
    get 'pag/:page', action: :index, on: :collection
  end

  delete "logout" => "sesiones#destroy", :as => "logout"
  get "login" => "sesiones#new", :as => "login"
  # get "signup" => "usuarios#new", :as => "signup"
  root :to => "sesiones#new"
  resources :usuarios, except: [:show, :destroy] do
    member do
      get 'change_pwd'
      patch 'update_pwd'
      patch 'reset_pwd'
    end
  end
  resources :sesiones, only: [:create, :new, :destroy]
end

app/models/cuenta.rb
class Cuenta < ApplicationRecord
	has_many :movimientos
	belongs_to :empresa

	validates :descripcion, presence: true
	validates_numericality_of :saldo_inicial, greather_than_or_equal_to: 0

  before_destroy :cuenta_con_movimientos?

	def self.all_for_select
		select(:descripcion, :id).where(habilitado: true).order(:descripcion).map { |t| [t.descripcion, t.id] }
	end

	def self.obtener_saldos(usuario)
    query = <<-SQL
      SUM(case when transacciones.es_debito = 't' then -movimientos.importe
               else movimientos.importe end) AS importe,
      MAX(movimientos.fecha_mov) AS max_fecha_mov,
      cuentas.descripcion AS descripcion_cuenta,
      cuentas.saldo_inicial
    SQL
    saldos_cuentas = usuario.cuentas.joins(movimientos: [:transaccion]).select(query)
                 .group("cuentas.descripcion, cuentas.saldo_inicial")
    return saldos_cuentas
	end

private
  def cuenta_con_movimientos?
    errors.add(:base, "No se puede eliminar una cuenta con movimientos.") if movimientos.any?
    throw(:abort) if errors.any?
  end
end

app/controllers/cuentas_controller.rb
class CuentasController < ApplicationController
  before_action :set_cuenta, only: [:show, :edit, :update, :destroy]

  # GET /cuentas
  # GET /cuentas.json
  def index
    @cuentas = current_user.cuentas.all
  end

  # GET /cuentas/1
  # GET /cuentas/1.json
  def show
  end

  # GET /cuentas/new
  def new
    @cuenta = Cuenta.new
  end

  # GET /cuentas/1/edit
  def edit
  end

  # POST /cuentas
  # POST /cuentas.json
  def create
    @cuenta = Cuenta.new(cuenta_params)
    @cuenta.empresa = current_user.empresa

    respond_to do |format|
      if @cuenta.save
        format.html { redirect_to cuentas_path, notice: 'La cuenta se creó correctamente.' }
        format.json { render :show, status: :created, location: @cuenta }
      else
        format.html { render :new }
        format.json { render json: @cuenta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cuentas/1
  # PATCH/PUT /cuentas/1.json
  def update
    respond_to do |format|
      if @cuenta.update(cuenta_params)
        format.html { redirect_to cuentas_path, notice: 'La cuenta se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @cuenta }
      else
        format.html { render :edit }
        format.json { render json: @cuenta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cuentas/1
  # DELETE /cuentas/1.json
  def destroy
    respond_to do |format|
      if @cuenta.destroy
        format.html { redirect_to cuentas_url, notice: 'La cuenta se eliminó correctamente.' }
        format.json { head :no_content }
      else
        format.html { redirect_to cuentas_path, error: @cuenta.errors.full_messages.join(" ") }
        format.json { render json: @cuenta.errors, status: :unprocessable_entity }
      end
    end
  end

  def saldos
    @cuentas = Cuenta.obtener_saldos(current_user)
    @total = @cuentas.sum(&:saldo_inicial) + @cuentas.sum(&:importe)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cuenta
      @cuenta = current_user.cuentas.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cuenta_params
      params.require(:cuenta).permit(:descripcion, :saldo_inicial, :habilitado)
    end
end

app/helpers/cuentas_helper.rb
module CuentasHelper
end

app/views/cuentas/_form.html.erb
<%= form_for(cuenta) do |f| %>
  <%= render 'errores', partial: true, model: cuenta, model_name: 'La cuenta' %>

  <div class="form-group">
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :saldo_inicial %>
    <%= f.text_field :saldo_inicial, value: currency_for_edition(cuenta.saldo_inicial), 
            class: 'form-control text-right' %>
  </div>

  <div class="checkbox">
    <%= f.label :habilitado do %>
      <%= f.check_box :habilitado %> 
      Habilitada
    <% end %>
  </div>  

  <%= render partial: "controls/form_actions", locals: { form: f, cancelar_path: cuentas_path} %>
<% end %>

app/views/cuentas/edit.html.erb
<% content_for :title, "Editando cuenta" %>

<h1>Editando Cuenta</h1>

<%= render 'form', cuenta: @cuenta %>

app/views/cuentas/index.html.erb
<% content_for :title, "Cuentas" %>

<div class="row">
  <h1 class="col-sm-3">Cuentas</h1>
  <div class="col-sm-6"><%= render 'notice' %></div>
  <div id="menu-abm" class="col-sm-3 text-right">
    <%= link_to 'Nueva cuenta', new_cuenta_path, class: 'btn btn-default', role: 'button' %>
  </div>
</div>

<% if @cuentas.any? %>
<table class="table table-striped table-responsive table-bordered">
  <thead>
    <tr>
      <th class="text-center">Descripción</th>
      <th class="text-center">Saldo inicial</th>
      <th class="text-center">Habilitado</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cuentas.each do |cuenta| %>
      <tr>
        <td><%= cuenta.descripcion %></td>
        <td class="text-right"><%= number_to_currency(cuenta.saldo_inicial) %></td>
        <td class="col-sm-2 text-center">
          <%= render partial: "controls/checkbox", object: cuenta.habilitado %>
        </td>
        <td class="text-center">
          <%= link_to edit_cuenta_path(cuenta) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
          <%= link_to cuenta, method: :delete, data: { confirm: '¿Está seguro?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <div id="notas-empty" class="row">
    <div class="alert alert-success text-center col-sm-4 col-sm-offset-4">
      Todavía no hay cuentas cargadas.
    </div>
  </div>
<% end %>

app/views/cuentas/new.html.erb
<% content_for :title, "Nueva cuenta" %>

<h1>Nueva Cuenta</h1>

<%= render 'form', cuenta: @cuenta %>

app/views/cuentas/saldos.html.erb
<% content_for :title, "Saldos de cuentas" %>

<div class="row">
  <h1 class="col-sm-12">Saldos de cuentas</h1>
</div>

<table class="table table-striped table-responsive table-bordered table-with-footer">
  <thead>
    <tr>
      <th class="text-center">Cuenta</th>
      <th class="text-center">Últ. Fec. Mov.</th>
      <th class="text-center">Importe</th>
    </tr>
  </thead>

  <tbody>
    <% @cuentas.each do |cuenta| %>
      <tr>
        <td><%= cuenta.descripcion_cuenta %></td>
        <td class="text-center"><%= I18n.localize Date.parse cuenta.max_fecha_mov, format: :fecmov %></td>
        <td class="text-right"><%= number_to_currency cuenta.saldo_inicial + cuenta.importe %></td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="2" class="text-right"><strong>Total: </strong></td>
      <td class="text-right"><%= number_to_currency @total %></td>
    </tr>
  </tfoot>
</table>

app/views/cuentas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @cuenta.descripcion %>
</p>

<p>
  <strong>Saldo inicial:</strong>
  <%= @cuenta.saldo_inicial %>
</p>

<%= link_to 'Edit', edit_cuenta_path(@cuenta) %> |
<%= link_to 'Back', cuentas_path %>